apiVersion: v2
name: dz4
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "17.2.0"
    repository: "https://charts.bitnami.com/bitnami"
